ALTER TABLE "changes" ALTER COLUMN "updated_at" SET DATA TYPE text COLLATE "C" USING to_char(to_timestamp("updated_at" / 1000) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS') || '.' || lpad(("updated_at" % 1000)::text, 3, '0') || 'Z';--> statement-breakpoint
ALTER TABLE "clients" ALTER COLUMN "updated_at" SET DATA TYPE text COLLATE "C" USING to_char(to_timestamp("updated_at" / 1000) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS') || '.' || lpad(("updated_at" % 1000)::text, 3, '0') || 'Z';--> statement-breakpoint
ALTER TABLE "projects" ALTER COLUMN "updated_at" SET DATA TYPE text COLLATE "C" USING to_char(to_timestamp("updated_at" / 1000) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS') || '.' || lpad(("updated_at" % 1000)::text, 3, '0') || 'Z';--> statement-breakpoint
ALTER TABLE "records" ALTER COLUMN "start" SET DATA TYPE text COLLATE "C" USING to_char(to_timestamp("start" / 1000) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS') || '.' || lpad(("start" % 1000)::text, 3, '0') || 'Z';--> statement-breakpoint
ALTER TABLE "records" ALTER COLUMN "stop" SET DATA TYPE text COLLATE "C" USING to_char(to_timestamp("stop" / 1000) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS') || '.' || lpad(("stop" % 1000)::text, 3, '0') || 'Z';--> statement-breakpoint
ALTER TABLE "records" ALTER COLUMN "updated_at" SET DATA TYPE text COLLATE "C" USING to_char(to_timestamp("updated_at" / 1000) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS') || '.' || lpad(("updated_at" % 1000)::text, 3, '0') || 'Z';--> statement-breakpoint
ALTER TABLE "tokens" ALTER COLUMN "created_at" SET DATA TYPE text COLLATE "C" USING to_char(to_timestamp("created_at" / 1000) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS') || '.' || lpad(("created_at" % 1000)::text, 3, '0') || 'Z';--> statement-breakpoint
ALTER TABLE "tokens" ALTER COLUMN "revoked_at" SET DATA TYPE text COLLATE "C" USING to_char(to_timestamp("revoked_at" / 1000) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS') || '.' || lpad(("revoked_at" % 1000)::text, 3, '0') || 'Z';--> statement-breakpoint
ALTER TABLE "workspaces" ALTER COLUMN "created_at" SET DATA TYPE text COLLATE "C" USING to_char(to_timestamp("created_at" / 1000) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS') || '.' || lpad(("created_at" % 1000)::text, 3, '0') || 'Z';--> statement-breakpoint
ALTER TABLE "workspaces" ALTER COLUMN "updated_at" SET DATA TYPE text COLLATE "C" USING to_char(to_timestamp("updated_at" / 1000) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS') || '.' || lpad(("updated_at" % 1000)::text, 3, '0') || 'Z';--> statement-breakpoint
UPDATE "changes" SET "payload" = jsonb_set("payload", '{createdAt}', to_jsonb(to_char(to_timestamp(("payload"->>'createdAt')::bigint / 1000) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS') || '.' || lpad((("payload"->>'createdAt')::bigint % 1000)::text, 3, '0') || 'Z')) WHERE jsonb_typeof("payload"->'createdAt') = 'number';--> statement-breakpoint
UPDATE "changes" SET "payload" = jsonb_set("payload", '{updatedAt}', to_jsonb(to_char(to_timestamp(("payload"->>'updatedAt')::bigint / 1000) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS') || '.' || lpad((("payload"->>'updatedAt')::bigint % 1000)::text, 3, '0') || 'Z')) WHERE jsonb_typeof("payload"->'updatedAt') = 'number';--> statement-breakpoint
UPDATE "changes" SET "payload" = jsonb_set("payload", '{start}', to_jsonb(to_char(to_timestamp(("payload"->>'start')::bigint / 1000) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS') || '.' || lpad((("payload"->>'start')::bigint % 1000)::text, 3, '0') || 'Z')) WHERE jsonb_typeof("payload"->'start') = 'number';--> statement-breakpoint
UPDATE "changes" SET "payload" = jsonb_set("payload", '{stop}', to_jsonb(to_char(to_timestamp(("payload"->>'stop')::bigint / 1000) AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS') || '.' || lpad((("payload"->>'stop')::bigint % 1000)::text, 3, '0') || 'Z')) WHERE jsonb_typeof("payload"->'stop') = 'number';
