export const channels = {
  listWorkspaces: 'timeStop:listWorkspaces',
  createWorkspace: 'timeStop:createWorkspace',
  updateWorkspace: 'timeStop:updateWorkspace',
  deleteWorkspace: 'timeStop:deleteWorkspace',
  listClients: 'timeStop:listClients',
  createClient: 'timeStop:createClient',
  updateClient: 'timeStop:updateClient',
  deleteClient: 'timeStop:deleteClient',
  listProjects: 'timeStop:listProjects',
  createProject: 'timeStop:createProject',
  updateProject: 'timeStop:updateProject',
  archiveProject: 'timeStop:archiveProject',
  unarchiveProject: 'timeStop:unarchiveProject',
  deleteProject: 'timeStop:deleteProject',
  countRecords: 'timeStop:countRecords',
  getContext: 'timeStop:getContext',
  setContext: 'timeStop:setContext',
  startTimer: 'timeStop:startTimer',
  stopTimer: 'timeStop:stopTimer',
  getTimer: 'timeStop:getTimer',
  updateRecordName: 'timeStop:updateRecordName',
  listRecords: 'timeStop:listRecords',
  timerChanged: 'timeStop:timerChanged',
} as const;
